### Handling Imbalance DataSet with ML

In [3]:
pip install imbalanced-learn

Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd

In [5]:
pd.pandas.set_option('display.max_columns',None)

In [7]:
df = pd.read_csv('/home/jangark20/Jupyter/002_test/creditcard.csv')
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10       V11       V12       V13       V14  \
0  0.098698  0.363787  0.090794 -0.551600 -0.617801 -0.991390 -0.311169   
1  0.085102 -0.255425 -0.166974  1.612727  1.065235  0.489095 -0.143772   
2  0.247676 -1.514654  0.207643  0.624501  0.066084  0.717293 -0.165946   
3  0.377436 -1.387024 -0.054952 -0.226487  0.178228  0.507757 -0.287924   
4 -0.270533  0.817739  0.753074 -0.822843  0.538196  1.345852 -1.119670   

        V15       V16       V17       V18       V19       V20       V21  \
0  1.468177 -0.470401  0.207971  0.025791  0.403993  0.251412 -0.018307   
1  0.635558  0.463917 -0.114805 -0.183361 -0.145783 -0.069083 -0.225775   
2  2.345865 -2.890083  1.109969 -0.121359 -2.261857  0.524980  0.247998   
3 -0.631418 -1.059647 -0.684093  1.965775 -1.232622 -0.208038 -0.108300   
4  0.175121 -0.451449 -0.237033 -0.038195  0.803487  0.408542 -0.009431   

        V22       V23       V24       V25       V26       V27       V28  \
0  0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1 -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2  0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3  0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4  0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   

   Amount  Class  
0  149.62      0  
1    2.69      0  
2  378.66      0  
3  123.50      0  
4   69.99      0

In [9]:
df.shape

(284807, 31)

In [11]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [13]:
## dependent feature is class 
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

0 has huge records and 1 has less records, so imbalanced dataset

In [44]:
## Independent and Depending features
x = df.drop('Class',axis=1)
y = df.Class

In [46]:
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report 
from sklearn.model_selection import KFold,GridSearchCV 
import numpy as np

In [64]:
log_class = LogisticRegression()
grid={'C':10.0 **np.arange(-2,3),'penalty':['l1','l2']}
cv=KFold(n_splits=5,random_state=None,shuffle=False)

In [66]:
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.7)

In [68]:
clf = GridSearchCV(log_class,grid,cv=cv,n_jobs=-1,scoring='f1_macro')
clf.fit(x_train,y_train)

/home/jangark20/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/jangark20/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logis

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [70]:
y_pred = clf.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85281    36]
 [   36    90]]
0.9991573329588147
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85317
           1       0.71      0.71      0.71       126

    accuracy                           1.00     85443
   macro avg       0.86      0.86      0.86     85443
weighted avg       1.00      1.00      1.00     85443



In [72]:
from sklearn.ensemble import RandomForestClassifier 
classifier = RandomForestClassifier()
classifier.fit(x_train,y_train)

RandomForestClassifier()

In [74]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85310     7]
 [   23   103]]
0.9996488887328394
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85317
           1       0.94      0.82      0.87       126

    accuracy                           1.00     85443
   macro avg       0.97      0.91      0.94     85443
weighted avg       1.00      1.00      1.00     85443



In [76]:
## Over Sampling 
y_train.value_counts()

Class
0    198998
1       366
Name: count, dtype: int64

In [90]:
class_weight=dict({0:1,1:543})

In [96]:
from sklearn.ensemble import RandomForestClassifier 
classifier = RandomForestClassifier(class_weight=class_weight)
classifier.fit(x_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 543})

In [98]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85313     4]
 [   23   103]]
0.9996839998595555
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85317
           1       0.96      0.82      0.88       126

    accuracy                           1.00     85443
   macro avg       0.98      0.91      0.94     85443
weighted avg       1.00      1.00      1.00     85443



In [100]:
from collections import Counter
Counter(y_train)

Counter({0: 198998, 1: 366})

In [130]:
from collections import Counter
from imblearn.under_sampling import NearMiss
ns = NearMiss(sampling_strategy='auto') 
x_train_ns, y_train_ns = ns.fit_resample(x_train, y_train)
print(f'The no. of classes befor fit {Counter(y_train)}')
print(f'The no. of classes after fit {Counter(y_train_ns)}')

The no. of classes befor fit Counter({0: 198998, 1: 366})
The no. of classes after fit Counter({0: 366, 1: 366})


In [132]:
from sklearn.ensemble import RandomForestClassifier 
classifier = RandomForestClassifier()
classifier.fit(x_train_ns,y_train_ns)

RandomForestClassifier()

In [134]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[57560 27757]
 [    1   125]]
0.6751284482052362
              precision    recall  f1-score   support

           0       1.00      0.67      0.81     85317
           1       0.00      0.99      0.01       126

    accuracy                           0.68     85443
   macro avg       0.50      0.83      0.41     85443
weighted avg       1.00      0.68      0.80     85443



### Over sampling 

In [137]:
from imblearn.over_sampling import RandomOverSampler

In [139]:
os = RandomOverSampler(sampling_strategy='auto')
x_train_os , y_train_os = os.fit_resample(x_train,y_train)
print(f'The no. of classes before fit {Counter(y_train)}')
print(f'The no of classes after fit {Counter(y_train_os)}')

The no. of classes before fit Counter({0: 198998, 1: 366})
The no of classes after fit Counter({0: 198998, 1: 198998})


In [141]:
from sklearn.ensemble import RandomForestClassifier 
classifier = RandomForestClassifier()
classifier.fit(x_train_os,y_train_os)

RandomForestClassifier()

In [143]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85312     5]
 [   22   104]]
0.9996839998595555
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85317
           1       0.95      0.83      0.89       126

    accuracy                           1.00     85443
   macro avg       0.98      0.91      0.94     85443
weighted avg       1.00      1.00      1.00     85443



### SMOTETomek

In [146]:
from imblearn.combine import SMOTETomek

In [148]:
sm = SMOTETomek(sampling_strategy='auto')
x_train_sm , y_train_sm = sm.fit_resample(x_train,y_train)
print(f'The no. of classes before fit {Counter(y_train)}')
print(f'The no of classes after fit {Counter(y_train_sm)}')

The no. of classes before fit Counter({0: 198998, 1: 366})
The no of classes after fit Counter({0: 198223, 1: 198223})


In [150]:
from sklearn.ensemble import RandomForestClassifier 
classifier = RandomForestClassifier()
classifier.fit(x_train_sm,y_train_sm)

RandomForestClassifier()

In [154]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85302    15]
 [   16   110]]
0.9996371850239341
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85317
           1       0.88      0.87      0.88       126

    accuracy                           1.00     85443
   macro avg       0.94      0.94      0.94     85443
weighted avg       1.00      1.00      1.00     85443



### Ensemble Technique

In [157]:
from imblearn.ensemble import EasyEnsembleClassifier

In [159]:
easy = EasyEnsembleClassifier()
easy.fit(x_train,y_train)

EasyEnsembleClassifier()

In [161]:
y_pred=easy.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[82180  3137]
 [    4   122]]
0.963238650328289
              precision    recall  f1-score   support

           0       1.00      0.96      0.98     85317
           1       0.04      0.97      0.07       126

    accuracy                           0.96     85443
   macro avg       0.52      0.97      0.53     85443
weighted avg       1.00      0.96      0.98     85443

